siteName: Pascaline
productionUrl: https://m4rrc0.github.io/poko-website-builder
languages:
  - code: fr
    status: published
    keepUrlPrefix: false
    customUrlPrefix:
      prefix: ''
    isWebsiteDefault: true
    isCmsDefault: true
    name: Français
collections:
  - people
newTabLinkTypes:
  - external
metadata:
  image: ''
